apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: test
    tier: webserver
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 80
  selector:
    app: test
    tier: webserver
