apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-php-test
  labels:
    name: k8s-php-test
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: k8s-php-test
    spec:
      containers:
        - name: k8s-php-test
          # TODO: set zone and project
          image: 'us.gcr.io/sgc-gke-tutorial/web1'
          imagePullPolicy: Always
          ports:
            - containerPort: 80
