apiVersion: v1
kind: ReplicationController
metadata:
  name: k8s-php-test
  labels:
    name: k8s-php-test
spec:
  replicas: 1
  selector:
    name: k8s-php-test
  template:
    metadata:
      labels:
        name: k8s-php-test
    spec:
      containers:
        - name: k8s-php-test
          image: bitgandtter/k8s_php_test
          ports:
            - containerPort: 80