apiVersion: v1
kind: Service
metadata:
  name: k8s-php-test
  labels:
    name: k8s-php-test
spec:
  ports:
    - protocol: TCP
    - name: web
      port: 80
      targetPort: 80
  selector:
    name: k8s-php-test
